fragment AddressFragment on AddressEntity {
  addressDetail
  addressName
  contactName
  contactPhone
  createdAt
  deletedAt
  id
  isDefault
  latitude
  longitude
  mapAddress
  updatedAt
  userId
}
