fragment VehicleFragment on VehicleEntity {
  addressMoreInfo
  avatar {
    createdAt
    fileSize
    fullOriginalUrl
    fullThumbUrl
    id
    isDeleted
    mimeType
    name
    originalUrl
    ownerId
    thumbUrl
    type
    updatedAt
  }
  avatarId
  createdAt
  deletedAt
  detail
  id
  latitude
  longitude
  manufacturer {
    createdAt
    deletedAt
    id
    isActive
    name
    type
    updatedAt
  }
  mapAddress
  model {
    createdAt
    deletedAt
    id
    isActive
    name
    type
    updatedAt
  }
  name
  operatingNumber
  operatingUnit
  ordinalNumber
  origin {
    createdAt
    deletedAt
    id
    isActive
    name
    type
    updatedAt
  }
  serialNumber
  updatedAt
  vehicleRegistrationPlate
  vehicleType {
    createdAt
    deletedAt
    id
    isActive
    name
    type
    updatedAt
  }
  vinNumber
  yearOfManufacture
}
