query partnersForBooking(
  $filters: [JSONObject!]
  $isActive: StatusEnum
  $isAgency: Boolean
  $isApproved: Boolean
  $isTechnician: Boolean
  $latitude: Float!
  $limit: Int
  $longitude: Float!
  $page: Int
  $search: String
  $sort: SortInput
  $sortBy: PartnersForBookingSortBy
) {
  partnersForBooking(
    filters: $filters
    isActive: $isActive
    isAgency: $isAgency
    isApproved: $isApproved
    isTechnician: $isTechnician
    latitude: $latitude
    limit: $limit
    longitude: $longitude
    page: $page
    search: $search
    sort: $sort
    sortBy: $sortBy
  ) {
    items {
      ...PartnerFragment
    }
    meta {
      currentPage
      itemCount
      itemsPerPage
      totalItems
      totalPages
    }
  }
}
