query userProducts(
  $filters: [JSONObject!]
  $isActive: StatusEnum
  $isAdmin: Boolean
  $isApproved: Boolean
  $isNew: Boolean
  $limit: Int
  $manufacturerIds: [String!]
  $modelIds: [String!]
  $originIds: [String!]
  $page: Int
  $partnerId: String
  $search: String
  $sort: SortInput
  $type: ProductTypeEnum
  $vehicleTypeIds: [String!]
  $excludeProductIds: [String!]
) {
  userProducts(
    excludeProductIds: $excludeProductIds
    filters: $filters
    isActive: $isActive
    isAdmin: $isAdmin
    isApproved: $isApproved
    isNew: $isNew
    limit: $limit
    manufacturerIds: $manufacturerIds
    modelIds: $modelIds
    originIds: $originIds
    page: $page
    partnerId: $partnerId
    search: $search
    sort: $sort
    type: $type
    vehicleTypeIds: $vehicleTypeIds
  ) {
    items {
      ...ProductFragment
    }
    meta {
      currentPage
      itemCount
      itemsPerPage
      totalItems
      totalPages
    }
  }
}
