export enum AppRoutes {
  //Auth route
  AUTH = 'AUTH',
  LOGIN = 'LOGIN',
  FREELANCER_REGISTER = 'FREELANCER_REGISTER',
  REGISTER = 'REGISTER',
  REGISTRATION_PASSWORD_CREATION = 'REGISTRATION_PASSWORD_CREATION',
  VERIFY_OTP = 'VERIFY_OTP',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  FREELANCER_REGISTER_SUCCESS = 'FREELANCER_REGISTER_SUCCESS',
  AREA_PICKER = 'AREA_PICKER',
  QUALIFICATION_SELECTOR = 'QUALIFICATION_SELECTOR',
  RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS',

  //App route
  APP = 'APP',
  MAP = 'MAP',
  SCREEN1 = 'SCREEN1',
  SCREEN2 = 'SCREEN2',

  ADDRESS = 'ADDRESS',
  ADDRESS_AUTOCOMPLETE = 'ADDRESS_AUTOCOMPLETE',
  ADDRESS_MAP = 'ADDRESS_MAP',

  // Common
  SELECT = 'SELECT',

  //Bottom Tab
  BOTTOM_TAB = 'BOTTOM_TAB',
  HOME = 'HOME',
  STORE = 'STORE',
  SERVICE = 'SERVICE',
  NOTIFICATION = 'NOTIFICATION',
  ACCOUNT = 'ACCOUNT',
  LEARNING = 'LEARNING',

  REPAIR_REQUEST_LIST_SCREEN = 'REPAIR_REQUEST_LIST_SCREEN',
  REPAIR_REQUEST_REQUEST_DETAIL_SCREEN = 'REPAIR_REQUEST_REQUEST_DETAIL_SCREEN',
  REPAIR_REQUEST_LIST_AWAITING_REQUEST = 'REPAIR_REQUEST_LIST_AWAITING_REQUEST',
  REPAIR_REQUEST_LIST_INPROGRESS_REQUEST = 'REPAIR_REQUEST_LIST_INPROGRESS_REQUEST',
  REPAIR_REQUEST_LIST_COMPLETED_REQUEST = 'REPAIR_REQUEST_LIST_COMPLETED_REQUEST',
  REPAIR_REQUEST_LIST_CANCELED_REQUEST = 'REPAIR_REQUEST_LIST_CANCELED_REQUEST',
  REPAIR_REQUEST_LIST_CHECKING_REQUEST = 'REPAIR_REQUEST_LIST_CHECKING_REQUEST',
  REPAIR_REQUEST_LIST_HAND_OVER = 'REPAIR_REQUEST_LIST_HAND_OVER',
  REPAIR_REQUEST_CANCEL_REQUEST = 'REPAIR_REQUEST_CANCEL_REQUEST',
  REPAIR_REQUEST_STATUS_HISTORY = 'REPAIR_REQUEST_STATUS_HISTORY',

  COURSE = 'COURSE',
  COURSE_DETAIL = 'COURSE_DETAIL',

  MALFUNCTION_SCREEN = 'MALFUNCTION_SCREEN',
  REPAIR_REQUEST_QUOTATION_FORM_SCREEN = 'REPAIR_REQUEST_QUOTATION_FORM_SCREEN',
  REPAIR_REQUEST_QUOTATION_CONFIRM_SCREEN = 'REPAIR_REQUEST_QUOTATION_CONFIRM_SCREEN',
  REPAIR_REQUEST_AGENCY_ASSIGN_TECHNICIAN = 'REPAIR_REQUEST_AGENCY_ASSIGN_TECHNICIAN',
  REPAIR_REQUEST_QUOTATION_REJECT_DETAIL = 'REPAIR_REQUEST_QUOTATION_REJECT_DETAIL',
  REPAIR_REQUEST_REVIEW_CUSTOMER = 'REPAIR_REQUEST_REVIEW_CUSTOMER',

  MEDIA_LIST_VIEW_SCREEN = 'MEDIA_LIST_VIEW_SCREEN',
  QUOTATION_HISTORY = 'QUOTATION_HISTORY',
  PRICE_HISTORY_DETAIL = 'PRICE_HISTORY_DETAIL',

  TECHNICIAN_LIST_SCREEN = 'TECHNICIAN_LIST_SCREEN',
  TECHNICIAN_DETAIL_SCREEN = 'TECHNICIAN_DETAIL_SCREEN',
  TECHNICIAN_REPAIR_HISTORY_TAB = 'TECHNICIAN_REPAIR_HISTORY_TAB',
  TECHNICIAN_REVIEW_TAB = 'TECHNICIAN_REVIEW_TAB',
  TECHNICIAN_RECEIPT_TAB = 'TECHNICIAN_RECEIPT_TAB',

  TECHNICIAN_REPAIR_DETAIL_SCREEN = 'TECHNICIAN_REPAIR_DETAIL_SCREEN',
  TECHNICIAN_REPAIR_REVIEW_TAB = 'TECHNICIAN_REPAIR_REVIEW_TAB',
  TECHNICIAN_REPAIR_DETAIL_TAB = 'TECHNICIAN_REPAIR_DETAIL_TAB',

  TECHNICIAN_RECEIPT_DETAIL_SCREEN = 'TECHNICIAN_RECEIPT_DETAIL_SCREEN',
  PARTNER_UPDATE_MY_INFO = 'PARTNER_UPDATE_MY_INFO',

  TECHNICIAN_INFORMATION_SCREEN = 'TECHNICIAN_INFORMATION_SCREEN',

  PRODUCT_LIST_SCREEN = 'PRODUCT_LIST_SCREEN',
  PRODUCT_ADD_SCREEN = 'PRODUCT_ADD_SCREEN',
  PRODUCT_ADD_VEHICLE_SCREEN = 'PRODUCT_ADD_VEHICLE_SCREEN',
  PRODUCT_ADD_VEHICLE_PREVIEW = 'PRODUCT_ADD_VEHICLE_PREVIEW',
  PART_SELECT_SCREEN = 'PART_SELECT_SCREEN',

  PRODUCT_ADD_ACCESSORY_SCREEN = 'PRODUCT_ADD_ACCESSORY_SCREEN',
  PRODUCT_ADD_ACCESSORY_SELECT_PART = 'PRODUCT_ADD_ACCESSORY_SELECT_PART',
  PRODUCT_VEHICLE_ACCESSORY_PREVIEW = 'PRODUCT_VEHICLE_ACCESSORY_PREVIEW',
  PRODUCT_ADD_SELECT_UNIT = 'PRODUCT_ADD_SELECT_UNIT',

  // SETTING
  ACCOUNT_ADDRESS = 'ACCOUNT_ADDRESS',
  ACCOUNT_ADDRESS_DETAIL = 'ACCOUNT_ADDRESS_DETAIL',
  ACCOUNT_EDITING = 'ACCOUNT_EDITING',
  ACCOUNT_CHANGE_PASSWORD = 'ACCOUNT_CHANGE_PASSWORD',
  ACCOUNT_SETTING = 'ACCOUNT_SETTING',

  //REQUEST PUSH
  REPAIR_REQUEST_REQUEST_PUSH_AGENCY = 'REPAIR_REQUEST_REQUEST_PUSH_AGENCY',
  REQUEST_PUSH_TECHNICIAN = 'REQUEST_PUSH_TECHNICIAN',
  REPAIR_REQUEST_RESCHEDULE_REQUEST = 'REPAIR_REQUEST_RESCHEDULE_REQUEST',
  REPAIR_REQUEST_CREATE_SETTLEMENT = 'REPAIR_REQUEST_CREATE_SETTLEMENT',

  //MY ORDER
  MY_ORDER_LIST_SCREEN = 'MY_ORDER_LIST_SCREEN',
  MY_ORDER_WAITING_SCREEN = 'MY_ORDER_WAITING_SCREEN',
  MY_ORDER_INPROGRESS_SCREEN = 'MY_ORDER_INPROGRESS_SCREEN',
  MY_ORDER_COMPLETED_SCREEN = 'MY_ORDER_COMPLETED_SCREEN',
  MY_ORDER_CANCELED_SCREEN = 'MY_ORDER_CANCELED_SCREEN',
  MY_ORDER_DETAIL_SCREEN = 'MY_ORDER_DETAIL_SCREEN',
  MY_ORDER_REVIEW_SCREEN = 'MY_ORDER_REVIEW_SCREEN',
  MY_ORDER_CANCEL_REASON_SCREEN = 'MY_ORDER_CANCEL_REASON_SCREEN',
  // PRODUCT QUOTATION
  PRODUCT_QUOTATION_LIST_SCREEN = 'PRODUCT_QUOTATION_LIST_SCREEN',
  PRODUCT_QUOTATION_DETAIL_SCREEN = 'PRODUCT_QUOTATION_DETAIL_SCREEN',
  //STORE
  REVIEW_STORE_SCREEN = 'REVIEW_STORE_SCREEN',
  //REVENUE
  REVENUE_SCREEN = 'REVENUE_SCREEN',
  REVENUE_FILTER_SCREEN = 'REVENUE_FILTER_SCREEN',
  //Voucher
  VOUCHER_SCREEN = 'VOUCHER_SCREEN',
  VOUCHER_ADD_SCREEN = 'VOUCHER_ADD_SCREEN',
  CHOOSE_PRODUCT = 'CHOOSE_PRODUCT',
  VOUCHER_ACTIVE_TAB = 'VOUCHER_ACTIVE_TAB',
  VOUCHER_INACTIVE_TAB = 'VOUCHER_INACTIVE_TAB',
  VOUCHER_DETAIL_SCREEN = 'VOUCHER_DETAIL_SCREEN',

  // Feedback
  FEEDBACK = 'FEEDBACK',
  FEEDBACK_DETAIL = 'FEEDBACK_DETAIL',
  FEEDBACK_CREATE = 'FEEDBACK_CREATE',
  //Document
  DOCUMENT_SCREEN = 'DOCUMENT_SCREEN',
  DOCUMENT_LIST_SCREEN = 'DOCUMENT_LIST_SCREEN',
  DOCUMENT_DETAIL_SCREEN = 'DOCUMENT_DETAIL_SCREEN',

  //SURVEY
  SURVEY_SCREEN = 'SURVEY_SCREEN',
  SURVEY_LIST_SCREEN = 'SURVEY_LIST_SCREEN',
  //Warehouse
  WAREHOUSE_LIST_SCREEN = 'WAREHOUSE_LIST_SCREEN',
  WAREHOUSE_DETAIL_SCREEN = 'WAREHOUSE_DETAIL_SCREEN',
  WAREHOUSE_ADD_SCREEN = 'WAREHOUSE_ADD_SCREEN',
  WAREHOUSE_IMPORT_EXPORT_PRODUCT_SCREEN = 'WAREHOUSE_IMPORT_EXPORT_PRODUCT_SCREEN',
  WAREHOUSE_IMPORT_TAB = 'WAREHOUSE_IMPORT_TAB',
  WAREHOUSE_EXPORT_TAB = 'WAREHOUSE_EXPORT_TAB',
  WAREHOUSE_WAREHOUSE_TAB = 'WAREHOUSE_WAREHOUSE_TAB',
}
