query getApproximateAddressUnits($input: ApproximateAddressUnitsArgs!) {
  getApproximateAddressUnits(input: $input) {
    district {
      code
      codename
      divisionType
      name
      shortCodename
    }
    province {
      code
      codename
      divisionType
      name
    }
    ward {
      code
      codename
      divisionType
      name
      shortCodename
    }
  }
}
