query userGetLatestQuotationOfBooking($bookingId: String!) {
  userGetLatestQuotationOfBooking(bookingId: $bookingId) {
    accessories {
      available
      createdAt
      deletedAt
      id
      name
      quantity
      quotationId
      unit
      unitPrice
      updatedAt
    }
    additionalFees {
      amount
      createdAt
      deletedAt
      id
      name
      quotationId
      updatedAt
    }
    booking {
      addressMoreInfo
      code
      createdAt
      deletedAt
      description
      id
      latitude
      longitude
      mapAddress
      medias {
        createdAt
        fileSize
        fullOriginalUrl
        fullThumbUrl
        id
        isDeleted
        mimeType
        name
        originalUrl
        ownerId
        thumbUrl
        type
        updatedAt
        videoUrl
      }
      partner {
        addressMoreInfo
        avatarId
        bank
        birthday
        cardNumber
        citizenId
        createdAt
        deletedAt
        description
        email
        fullname
        hotline
        id
        isActive
        isApproved
        latitude
        longitude
        mapAddress
        parentId
        phone
        suggestionPoint
        type
        updatedAt
        reviewSummary {
          starAverage
          total
          percent
        }
      }
      partnerId
      problemTexts
      problems {
        createdAt
        deletedAt
        id
        isActive
        name
        type
        updatedAt
      }
      scheduleReason
      scheduleTime
      status
      statusDetail {
        bookingId
        createdAt
        id
        note
        partnerId
        scheduleReason
        scheduleTime
        status
        userId
      }
      technician {
        addressMoreInfo
        avatarId
        bank
        birthday
        cardNumber
        citizenId
        createdAt
        deletedAt
        description
        email
        fullname
        hotline
        id
        isActive
        isApproved
        latitude
        longitude
        mapAddress
        parentId
        phone
        suggestionPoint
        type
        updatedAt
        reviewSummary {
          starAverage
          total
          percent
        }
      }
      technicianId
      transportDistance
      transportDuration
      transportFee
      updatedAt
      user {
        address
        avatarId
        birthday
        certificate
        createdAt
        deletedAt
        email
        fullname
        id
        isActive
        phone
        totalBookings
        totalMaintenanceRequests
        totalOrders
        totalSpending
        updatedAt
      }
      userId
      vehicle {
        addressMoreInfo
        avatarId
        createdAt
        deletedAt
        detail
        hidden
        id
        latitude
        longitude
        mapAddress
        name
        operatingNumber
        operatingUnit
        ordinalNumber
        serialNumber
        updatedAt
        userId
        vehicleRegistrationPlate
        vinNumber
        yearOfManufacture
      }
      vehicleId
    }
    bookingId
    createdAt
    deletedAt
    diagnosisFee
    diagnosisNote
    diagnostics {
      createdAt
      deletedAt
      diagnosticCode
      expense
      id
      quotationId
      updatedAt
    }
    estimatedCompleteAt
    id
    operatingNumber
    operatingUnit
    rejectReasons
    reasons {
      createdAt
      deletedAt
      id
      isActive
      name
      type
      updatedAt
    }
    repairFee
    status
    technicianId
    total
    transportFee
    updatedAt
    userId
  }
}
