fragment PartnerFragment on PartnerEntity {
  addressMoreInfo
  avatar {
    ...MediaFragment
  }
  avatarId
  bank
  birthday
  cardNumber
  citizenId
  createdAt
  deletedAt
  description
  education {
    createdAt
    deletedAt
    id
    isActive
    name
    type
    updatedAt
  }
  email
  expenseInfo {
    cost
    distance
    time
  }
  fullname
  hotline
  id
  isActive
  isApproved
  latitude
  longitude
  mapAddress
  parentId
  phone
  qualifications {
    createdAt
    deletedAt
    id
    isActive
    name
    type
    updatedAt
  }
  reviewSummary {
    percent
    starAverage
    total
  }
  starInfo {
    star
    total
  }
  suggestionPoint
  type
  updatedAt
}
