query agencyGetTechnicians(
  $filters: [JSONObject!]
  $isActive: StatusEnum
  $isApproved: Boolean
  $limit: Int
  $page: Int
  $search: String
  $sort: SortInput
) {
  agencyGetTechnicians(
    filters: $filters
    isActive: $isActive
    isApproved: $isApproved
    limit: $limit
    page: $page
    search: $search
    sort: $sort
  ) {
    items {
      fullname
      id
      phone
      avatar {
        fullThumbUrl
      }
      qualifications {
        id
        isActive
        name
        type
      }
      reviewSummary {
        starAverage
        total
        percent
      }
    }
    meta {
      currentPage
      itemCount
      itemsPerPage
      totalItems
      totalPages
    }
  }
}
